[2024-07-13T14:37:19.779+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-13T14:37:19.796+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chess_etl.redshift_game_load scheduled__2024-06-01T00:00:00+00:00 [queued]>
[2024-07-13T14:37:19.803+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chess_etl.redshift_game_load scheduled__2024-06-01T00:00:00+00:00 [queued]>
[2024-07-13T14:37:19.803+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-13T14:37:19.813+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): redshift_game_load> on 2024-06-01 00:00:00+00:00
[2024-07-13T14:37:19.819+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=899) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-13T14:37:19.821+0000] {standard_task_runner.py:63} INFO - Started process 901 to run task
[2024-07-13T14:37:19.820+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chess_etl', 'redshift_game_load', 'scheduled__2024-06-01T00:00:00+00:00', '--job-id', '828', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmp136zmsdi']
[2024-07-13T14:37:19.821+0000] {standard_task_runner.py:91} INFO - Job 828: Subtask redshift_game_load
[2024-07-13T14:37:19.861+0000] {task_command.py:426} INFO - Running <TaskInstance: chess_etl.redshift_game_load scheduled__2024-06-01T00:00:00+00:00 [running]> on host 9bf11a4173a0
[2024-07-13T14:37:19.922+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chess_etl' AIRFLOW_CTX_TASK_ID='redshift_game_load' AIRFLOW_CTX_EXECUTION_DATE='2024-06-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-01T00:00:00+00:00'
[2024-07-13T14:37:19.923+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-13T14:37:19.923+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-07-13T14:37:19.929+0000] {base.py:84} INFO - Using connection ID 'chess_project_s3' for task execution.
[2024-07-13T14:37:20.812+0000] {base.py:84} INFO - Using connection ID 'chess_project_redshift' for task execution.
[2024-07-13T14:37:38.188+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-13T14:37:38.189+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/redshift_connector/core.py", line 1821, in execute
    ps = cache["ps"][key]
         ~~~~~~~~~~~^^^^^
KeyError: ('\n    with staging as (\n    select COUNT(*) as rows FROM "dev"."chess_project_staging"."game"\n    WHERE dateid >= date \'{execution_date}\' and dateid < dateadd(month, 1, \'{execution_date}\')\n    ), \n    prod as (\n    select COUNT(*) as rows FROM "dev"."chess_project"."game"\n    WHERE dateid >= date \'{execution_date}\' and dateid < dateadd(month, 1, \'{execution_date}\')\n    )\n    select (staging.rows>=prod.rows)::int as check from staging, prod\n    ', ())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/chess_dag.py", line 27, in redshift_game_task
    return load_game_data(execution_date)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/redshift_etl_code.py", line 102, in load_game_data
    cursor.execute(check_games_query)
  File "/home/airflow/.local/lib/python3.12/site-packages/redshift_connector/cursor.py", line 248, in execute
    raise e
  File "/home/airflow/.local/lib/python3.12/site-packages/redshift_connector/cursor.py", line 241, in execute
    self._c.execute(self, operation, args)
  File "/home/airflow/.local/lib/python3.12/site-packages/redshift_connector/core.py", line 1902, in execute
    self.handle_messages(cursor)
  File "/home/airflow/.local/lib/python3.12/site-packages/redshift_connector/core.py", line 2194, in handle_messages
    raise self.error
redshift_connector.error.ProgrammingError: {'S': 'ERROR', 'C': '22007', 'M': 'invalid input syntax for type date: "{execution_date}"', 'F': '../src/pg/src/backend/utils/adt/adt_datetime.c', 'L': '3331', 'R': 'DateTimeParseError'}
[2024-07-13T14:37:38.199+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=chess_etl, task_id=redshift_game_load, run_id=scheduled__2024-06-01T00:00:00+00:00, execution_date=20240601T000000, start_date=20240713T143719, end_date=20240713T143738
[2024-07-13T14:37:38.209+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 828 for task redshift_game_load ({'S': 'ERROR', 'C': '22007', 'M': 'invalid input syntax for type date: "{execution_date}"', 'F': '../src/pg/src/backend/utils/adt/adt_datetime.c', 'L': '3331', 'R': 'DateTimeParseError'}; 901)
[2024-07-13T14:37:38.256+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-13T14:37:38.271+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-13T14:37:38.275+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
