[2024-07-07T19:02:37.408+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-07T19:02:37.420+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chess_etl.blunders_etl backfill__2019-03-01T00:00:00+00:00 [queued]>
[2024-07-07T19:02:37.425+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chess_etl.blunders_etl backfill__2019-03-01T00:00:00+00:00 [queued]>
[2024-07-07T19:02:37.425+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-07T19:02:37.433+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): blunders_etl> on 2019-03-01 00:00:00+00:00
[2024-07-07T19:02:37.441+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=124) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-07T19:02:37.442+0000] {standard_task_runner.py:63} INFO - Started process 126 to run task
[2024-07-07T19:02:37.442+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chess_etl', 'blunders_etl', 'backfill__2019-03-01T00:00:00+00:00', '--job-id', '494', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmp_02reem6']
[2024-07-07T19:02:37.443+0000] {standard_task_runner.py:91} INFO - Job 494: Subtask blunders_etl
[2024-07-07T19:02:37.471+0000] {task_command.py:426} INFO - Running <TaskInstance: chess_etl.blunders_etl backfill__2019-03-01T00:00:00+00:00 [running]> on host 1c777a41c043
[2024-07-07T19:02:37.519+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chess_etl' AIRFLOW_CTX_TASK_ID='blunders_etl' AIRFLOW_CTX_EXECUTION_DATE='2019-03-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='backfill__2019-03-01T00:00:00+00:00'
[2024-07-07T19:02:37.521+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-07T19:02:37.521+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-07-07T19:02:37.526+0000] {base.py:84} INFO - Using connection ID 'chess_project_s3' for task execution.
[2024-07-07T19:03:48.783+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-07T19:03:48.784+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-07T19:03:48.790+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=chess_etl, task_id=blunders_etl, run_id=backfill__2019-03-01T00:00:00+00:00, execution_date=20190301T000000, start_date=20240707T190237, end_date=20240707T190348
[2024-07-07T19:03:48.840+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-07T19:03:48.851+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-07T19:03:48.852+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-07T20:30:06.977+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-07T20:30:06.991+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chess_etl.blunders_etl backfill__2019-03-01T00:00:00+00:00 [queued]>
[2024-07-07T20:30:06.997+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chess_etl.blunders_etl backfill__2019-03-01T00:00:00+00:00 [queued]>
[2024-07-07T20:30:06.998+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-07T20:30:07.008+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): blunders_etl> on 2019-03-01 00:00:00+00:00
[2024-07-07T20:30:07.014+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=95) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-07T20:30:07.014+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chess_etl', 'blunders_etl', 'backfill__2019-03-01T00:00:00+00:00', '--job-id', '504', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmppa6kqluq']
[2024-07-07T20:30:07.015+0000] {standard_task_runner.py:63} INFO - Started process 97 to run task
[2024-07-07T20:30:07.015+0000] {standard_task_runner.py:91} INFO - Job 504: Subtask blunders_etl
[2024-07-07T20:30:07.049+0000] {task_command.py:426} INFO - Running <TaskInstance: chess_etl.blunders_etl backfill__2019-03-01T00:00:00+00:00 [running]> on host 6569f5155f0c
[2024-07-07T20:30:07.111+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chess_etl' AIRFLOW_CTX_TASK_ID='blunders_etl' AIRFLOW_CTX_EXECUTION_DATE='2019-03-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='backfill__2019-03-01T00:00:00+00:00'
[2024-07-07T20:30:07.112+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-07T20:30:07.113+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-07-07T20:30:07.119+0000] {base.py:84} INFO - Using connection ID 'chess_project_s3' for task execution.
[2024-07-07T20:30:15.762+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-07T20:30:15.763+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/chess_dag.py", line 23, in blunders_etl_task
    return get_monthly_blunders(execution_date)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/blunder_etl_code.py", line 106, in get_monthly_blunders
    df_blunders.loc[n]=[url] + [day] + [daynum] + blunder
    ~~~~~~~~~~~~~~~^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/indexing.py", line 885, in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/indexing.py", line 1883, in _setitem_with_indexer
    self._setitem_with_indexer_missing(indexer, value)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/indexing.py", line 2219, in _setitem_with_indexer_missing
    raise ValueError("cannot set a row with mismatched columns")
ValueError: cannot set a row with mismatched columns
[2024-07-07T20:30:15.773+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=chess_etl, task_id=blunders_etl, run_id=backfill__2019-03-01T00:00:00+00:00, execution_date=20190301T000000, start_date=20240707T203006, end_date=20240707T203015
[2024-07-07T20:30:15.782+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 504 for task blunders_etl (cannot set a row with mismatched columns; 97)
[2024-07-07T20:30:15.800+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-07T20:30:15.809+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-07T20:30:15.810+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
