[2024-07-07T21:13:27.682+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-07T21:13:27.695+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chess_etl.redshift_move_load backfill__2019-03-01T00:00:00+00:00 [queued]>
[2024-07-07T21:13:27.700+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chess_etl.redshift_move_load backfill__2019-03-01T00:00:00+00:00 [queued]>
[2024-07-07T21:13:27.701+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-07T21:13:27.709+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): redshift_move_load> on 2019-03-01 00:00:00+00:00
[2024-07-07T21:13:27.714+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1047) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-07T21:13:27.715+0000] {standard_task_runner.py:63} INFO - Started process 1049 to run task
[2024-07-07T21:13:27.715+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chess_etl', 'redshift_move_load', 'backfill__2019-03-01T00:00:00+00:00', '--job-id', '556', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmpfswlufit']
[2024-07-07T21:13:27.716+0000] {standard_task_runner.py:91} INFO - Job 556: Subtask redshift_move_load
[2024-07-07T21:13:27.745+0000] {task_command.py:426} INFO - Running <TaskInstance: chess_etl.redshift_move_load backfill__2019-03-01T00:00:00+00:00 [running]> on host 6569f5155f0c
[2024-07-07T21:13:27.800+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chess_etl' AIRFLOW_CTX_TASK_ID='redshift_move_load' AIRFLOW_CTX_EXECUTION_DATE='2019-03-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='backfill__2019-03-01T00:00:00+00:00'
[2024-07-07T21:13:27.801+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-07T21:13:27.801+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-07-07T21:13:27.807+0000] {base.py:84} INFO - Using connection ID 'chess_project_s3' for task execution.
[2024-07-07T21:13:28.624+0000] {base.py:84} INFO - Using connection ID 'chess_project_redshift' for task execution.
[2024-07-07T21:13:49.027+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-07T21:13:49.028+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/redshift_connector/core.py", line 1821, in execute
    ps = cache["ps"][key]
         ~~~~~~~~~~~^^^^^
KeyError: ('\n    INSERT INTO "dev"."chess_project"."move" (\n        SELECT \n            game_url,\n            date,\n            san,\n            uci,\n            side,\n            colour,\n            move,\n            game_state_before,\n            evaluation_type_before,\n            evaluation_before,\n            material_evaluation_before,\n            game_state_after,\n            evaluation_type_after,\n            evaluation_after,\n            material_evaluation_after  \n        FROM \n            "dev"."chess_project_staging"."move"\n        WHERE \n            dateid >= date \'2019-03-01 00:00:00+00:00\' and dateid < dateadd(month, 1, \'2019-03-01 00:00:00+00:00\')\n    )\n    ', ())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/chess_dag.py", line 31, in redshift_move_task
    return load_move_data(execution_date)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/redshift_etl_code.py", line 168, in load_move_data
    cursor.execute(insert_moves_query)
  File "/home/airflow/.local/lib/python3.12/site-packages/redshift_connector/cursor.py", line 248, in execute
    raise e
  File "/home/airflow/.local/lib/python3.12/site-packages/redshift_connector/cursor.py", line 241, in execute
    self._c.execute(self, operation, args)
  File "/home/airflow/.local/lib/python3.12/site-packages/redshift_connector/core.py", line 1902, in execute
    self.handle_messages(cursor)
  File "/home/airflow/.local/lib/python3.12/site-packages/redshift_connector/core.py", line 2194, in handle_messages
    raise self.error
redshift_connector.error.ProgrammingError: {'S': 'ERROR', 'C': '42703', 'M': 'column "date" does not exist in move', 'F': '../src/pg/src/backend/parser/parse_expr.c', 'L': '1944', 'R': 'transformColumnRef'}
[2024-07-07T21:13:49.036+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=chess_etl, task_id=redshift_move_load, run_id=backfill__2019-03-01T00:00:00+00:00, execution_date=20190301T000000, start_date=20240707T211327, end_date=20240707T211349
[2024-07-07T21:13:49.046+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 556 for task redshift_move_load ({'S': 'ERROR', 'C': '42703', 'M': 'column "date" does not exist in move', 'F': '../src/pg/src/backend/parser/parse_expr.c', 'L': '1944', 'R': 'transformColumnRef'}; 1049)
[2024-07-07T21:13:49.057+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-07T21:13:49.070+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-07T21:13:49.071+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
